In [824]:
# Data manipulation and processing
import pandas as pd
import numpy as np
import random
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# Neural network (Deep Learning)
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [825]:
df = pd.read_csv('train.csv')

In [826]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status,loan_id
0,26.0,male,Associate,256862.0,2,MORTGAGE,35000.0,EDUCATION,10.65,0.14,2.0,643,No,1,113
1,23.0,female,Associate,70430.0,0,MORTGAGE,6455.0,VENTURE,10.24,0.09,3.0,623,Yes,0,35501
2,33.0,male,Associate,75456.0,10,RENT,7000.0,MEDICAL,7.03,0.09,9.0,638,No,0,34764
3,27.0,female,Associate,25052.0,7,RENT,5500.0,PERSONAL,7.43,0.22,8.0,695,Yes,0,40540
4,30.0,female,Bachelor,61291.0,8,MORTGAGE,3984.0,DEBTCONSOLIDATION,10.86,0.06,9.0,687,No,0,37035

In [827]:
features = df[["person_age", "person_income", "person_emp_exp", "person_home_ownership", "loan_amnt", "loan_intent",
               "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length", "credit_score", "previous_loan_defaults_on_file"]]

In [828]:
target = df['loan_status']

In [829]:
features

,person_age,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
0,26.0,256862.0,2,MORTGAGE,35000.0,EDUCATION,10.65,0.14,2.0,643,No
1,23.0,70430.0,0,MORTGAGE,6455.0,VENTURE,10.24,0.09,3.0,623,Yes
2,33.0,75456.0,10,RENT,7000.0,MEDICAL,7.03,0.09,9.0,638,No
3,27.0,25052.0,7,RENT,5500.0,PERSONAL,7.43,0.22,8.0,695,Yes
4,30.0,61291.0,8,MORTGAGE,3984.0,DEBTCONSOLIDATION,10.86,0.06,9.0,687,No
...,...,...,...,...,...,...,...,...,...,...,...
31495,25.0,84983.0,3,RENT,12000.0,MEDICAL,10.37,0.14,3.0,618,Yes
31496,25.0,103044.0,0,MORTGAGE,7200.0,VENTURE,13.57,0.07,3.0,673,Yes
31497,26.0,60634.0,6,RENT,8470.0,HOMEIMPROVEMENT,10.95,0.14,5.0,653,No
31498,22.0,61414.0,0,MORTGAGE,12000.0,VENTURE,7.90,0.20,3.0,618,Yes
31499,22.0,80607.0,0,RENT,8000.0,HOMEIMPROVEMENT,14.65,0.10,4.0,659,No

In [830]:
target

0        1
1        0
2        0
3        0
4        0
        ..
31495    0
31496    0
31497    0
31498    0
31499    1
Name: loan_status, Length: 31500, dtype: int64

In [831]:
X = features.values
Y = target.values

In [832]:
X

array([[26.0, 256862.0, 2, ..., 2.0, 643, 'No'],
       [23.0, 70430.0, 0, ..., 3.0, 623, 'Yes'],
       [33.0, 75456.0, 10, ..., 9.0, 638, 'No'],
       ...,
       [26.0, 60634.0, 6, ..., 5.0, 653, 'No'],
       [22.0, 61414.0, 0, ..., 3.0, 618, 'Yes'],
       [22.0, 80607.0, 0, ..., 4.0, 659, 'No']], dtype=object)

In [833]:
X.shape

(31500, 11)

In [834]:
Y.shape

(31500,)

In [835]:
X = pd.get_dummies(features)

In [836]:
X

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_No,previous_loan_defaults_on_file_Yes
0,26.0,256862.0,2,35000.0,10.65,0.14,2.0,643,True,False,False,False,False,True,False,False,False,False,True,False
1,23.0,70430.0,0,6455.0,10.24,0.09,3.0,623,True,False,False,False,False,False,False,False,False,True,False,True
2,33.0,75456.0,10,7000.0,7.03,0.09,9.0,638,False,False,False,True,False,False,False,True,False,False,True,False
3,27.0,25052.0,7,5500.0,7.43,0.22,8.0,695,False,False,False,True,False,False,False,False,True,False,False,True
4,30.0,61291.0,8,3984.0,10.86,0.06,9.0,687,True,False,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31495,25.0,84983.0,3,12000.0,10.37,0.14,3.0,618,False,False,False,True,False,False,False,True,False,False,False,True
31496,25.0,103044.0,0,7200.0,13.57,0.07,3.0,673,True,False,False,False,False,False,False,False,False,True,False,True
31497,26.0,60634.0,6,8470.0,10.95,0.14,5.0,653,False,False,False,True,False,False,True,False,False,False,True,False
31498,22.0,61414.0,0,12000.0,7.90,0.20,3.0,618,True,False,False,False,False,False,False,False,False,True,False,True
31499,22.0,80607.0,0,8000.0,14.65,0.10,4.0,659,False,False,False,True,False,False,True,False,False,False,True,False

In [837]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [838]:
X

array([[-0.28856814,  1.98163245, -0.55805078, ..., -0.46033831,
         1.01496917, -1.01496917],
       [-0.78546481, -0.11764347, -0.88810954, ...,  2.17231541,
        -0.9852516 ,  0.9852516 ],
       [ 0.87085743, -0.06104932,  0.76218427, ..., -0.46033831,
         1.01496917, -1.01496917],
       ...,
       [-0.28856814, -0.22794915,  0.10206674, ..., -0.46033831,
         1.01496917, -1.01496917],
       [-0.95109704, -0.21916613, -0.88810954, ...,  2.17231541,
        -0.9852516 ,  0.9852516 ],
       [-0.95109704, -0.00304764, -0.88810954, ..., -0.46033831,
         1.01496917, -1.01496917]])

In [839]:
seed_value = 42
tf.random.set_seed(seed_value)    # For TensorFlow and Keras
np.random.seed(seed_value)        # For NumPy
random.seed(seed_value)
os.environ['PYTHONHASHSEED'] = str(seed_value)

In [840]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=seed_value)

In [841]:
lg = LogisticRegression()
lg.fit(X_train, Y_train)

LogisticRegression()

In [842]:
lg.score = lg.score(X_test, Y_test)

In [843]:
lg.score

0.8915873015873016

In [844]:
kn = KNeighborsClassifier()
kn.fit(X_train, Y_train)

KNeighborsClassifier()

In [845]:
kn.score = kn.score(X_test, Y_test)

In [846]:
kn.score

0.8990476190476191

In [847]:
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)

RandomForestClassifier()

In [848]:
rf.score = rf.score(X_test, Y_test)

In [849]:
rf.score

0.9234920634920635

In [850]:
input_dim = X_train.shape[1]

In [851]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [852]:
model.compile(optimizer='sgd',loss='binary_crossentropy', metrics=['accuracy'])

In [853]:
model.fit(X, Y, batch_size=32, epochs=30)

Epoch 1/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 211us/step - accuracy: 0.8296 - loss: 0.3953
Epoch 2/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 205us/step - accuracy: 0.8941 - loss: 0.2327
Epoch 3/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 198us/step - accuracy: 0.8984 - loss: 0.2214
Epoch 4/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step - accuracy: 0.9025 - loss: 0.2155
Epoch 5/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 206us/step - accuracy: 0.9053 - loss: 0.2113
Epoch 6/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 207us/step - accuracy: 0.9066 - loss: 0.2078
Epoch 7/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step - accuracy: 0.9079 - loss: 0.2047
Epoch 8/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step - accuracy: 0.9089 - loss: 0.2018
Epoch 9/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 210us/step - accuracy: 0.9106 - loss: 0.1994
Epoch 10/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 204us/step - accuracy: 0.9114 - loss: 0.1974
Epoch 11/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - accuracy: 0.9116 - loss: 0.1956
Epoch 12/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 238us/step - accuracy: 0.9131 - loss: 0.1941
Epoch 13/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 195us/step - accuracy: 0.9125 - loss: 0.1928
Epoch 14/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - accuracy: 0.9135 - loss: 0.1917
Epoch 15/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - accuracy: 0.9142 - loss: 0.1909
Epoch 16/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 191us/step - accuracy: 0.9144 - loss: 0.1901
Epoch 17/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - accuracy: 0.9149 - loss: 0.1893
Epoch 18/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - accuracy: 0.9152 - loss: 0.1887
Epoch 19/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 191us/step - accuracy: 0.9153 - loss: 0.1881
Epoch 20/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - accuracy: 0.9149 - loss: 0.1874
Epoch 21/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - accuracy: 0.9150 - loss: 0.1869
Epoch 22/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step - accuracy: 0.9155 - loss: 0.1863
Epoch 23/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 195us/step - accuracy: 0.9154 - loss: 0.1857
Epoch 24/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - accuracy: 0.9158 - loss: 0.1852
Epoch 25/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 195us/step - accuracy: 0.9161 - loss: 0.1846
Epoch 26/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 205us/step - accuracy: 0.9158 - loss: 0.1841
Epoch 27/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - accuracy: 0.9159 - loss: 0.1835
Epoch 28/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 191us/step - accuracy: 0.9166 - loss: 0.1830
Epoch 29/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - accuracy: 0.9171 - loss: 0.1824
Epoch 30/30
985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 186us/step - accuracy: 0.9171 - loss: 0.1819

In [854]:
model.evaluate(X_test, Y_test)

197/197 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step - accuracy: 0.9135 - loss: 0.1859

[0.18297703564167023, 0.9153968095779419]

In [855]:
test_df = pd.read_csv('test.csv')

In [856]:
test_df.dropna(inplace=True)

In [857]:
test_features = df[["person_age", "person_income", "person_emp_exp", "person_home_ownership", "loan_amnt", "loan_intent",
               "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length", "credit_score", "previous_loan_defaults_on_file"]]

In [858]:
X_tester = features.values
X_tester

array([[26.0, 256862.0, 2, ..., 2.0, 643, 'No'],
       [23.0, 70430.0, 0, ..., 3.0, 623, 'Yes'],
       [33.0, 75456.0, 10, ..., 9.0, 638, 'No'],
       ...,
       [26.0, 60634.0, 6, ..., 5.0, 653, 'No'],
       [22.0, 61414.0, 0, ..., 3.0, 618, 'Yes'],
       [22.0, 80607.0, 0, ..., 4.0, 659, 'No']], dtype=object)

In [859]:
X_tester = pd.get_dummies(test_features)

In [860]:
X_tester

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_No,previous_loan_defaults_on_file_Yes
0,26.0,256862.0,2,35000.0,10.65,0.14,2.0,643,True,False,False,False,False,True,False,False,False,False,True,False
1,23.0,70430.0,0,6455.0,10.24,0.09,3.0,623,True,False,False,False,False,False,False,False,False,True,False,True
2,33.0,75456.0,10,7000.0,7.03,0.09,9.0,638,False,False,False,True,False,False,False,True,False,False,True,False
3,27.0,25052.0,7,5500.0,7.43,0.22,8.0,695,False,False,False,True,False,False,False,False,True,False,False,True
4,30.0,61291.0,8,3984.0,10.86,0.06,9.0,687,True,False,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31495,25.0,84983.0,3,12000.0,10.37,0.14,3.0,618,False,False,False,True,False,False,False,True,False,False,False,True
31496,25.0,103044.0,0,7200.0,13.57,0.07,3.0,673,True,False,False,False,False,False,False,False,False,True,False,True
31497,26.0,60634.0,6,8470.0,10.95,0.14,5.0,653,False,False,False,True,False,False,True,False,False,False,True,False
31498,22.0,61414.0,0,12000.0,7.90,0.20,3.0,618,True,False,False,False,False,False,False,False,False,True,False,True
31499,22.0,80607.0,0,8000.0,14.65,0.10,4.0,659,False,False,False,True,False,False,True,False,False,False,True,False

In [861]:
X_tester = sc.fit_transform(X_tester)

In [862]:
X_tester

array([[-0.28856814,  1.98163245, -0.55805078, ..., -0.46033831,
         1.01496917, -1.01496917],
       [-0.78546481, -0.11764347, -0.88810954, ...,  2.17231541,
        -0.9852516 ,  0.9852516 ],
       [ 0.87085743, -0.06104932,  0.76218427, ..., -0.46033831,
         1.01496917, -1.01496917],
       ...,
       [-0.28856814, -0.22794915,  0.10206674, ..., -0.46033831,
         1.01496917, -1.01496917],
       [-0.95109704, -0.21916613, -0.88810954, ...,  2.17231541,
        -0.9852516 ,  0.9852516 ],
       [-0.95109704, -0.00304764, -0.88810954, ..., -0.46033831,
         1.01496917, -1.01496917]])

In [863]:
predictions = model.predict(X_tester)

985/985 ━━━━━━━━━━━━━━━━━━━━ 0s 182us/step

In [864]:
predictions = np.where(predictions > 0.5, 1, 0)

In [865]:
predictions

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [866]:
np.set_printoptions(threshold= 1000)
predictions = predictions.reshape(1, -1)[0]
predictions

array([0, 0, 0, ..., 0, 0, 1])

In [867]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(Y, predictions)
mse = mean_squared_error(Y, predictions)

In [868]:
mse

0.08066666666666666

In [869]:
mae

0.08066666666666666

In [870]:
train_data = pd.read_csv('train.csv')  
test_data = pd.read_csv('test.csv')   

X = train_data.drop(['loan_status'], axis=1)  
Y = train_data['loan_status']

X = pd.get_dummies(X)
X_test = pd.get_dummies(test_data)


X_test = X_test.reindex(columns=X.columns, fill_value=0)


X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=0.2, random_state=42)


sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)
X_tester = sc.transform(X_test)


dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, Y_train)
dt_predictions = dt_model.predict(X_val)
dt_accuracy = accuracy_score(Y_val, dt_predictions)
print("Decision Tree Accuracy:", dt_accuracy)

svm_model = SVC(kernel='linear')
svm_model.fit(X_train, Y_train)
svm_predictions = svm_model.predict(X_val)
svm_accuracy = accuracy_score(Y_val, svm_predictions)
print("SVM Accuracy:", svm_accuracy)

Decision Tree Accuracy: 0.9249206349206349
SVM Accuracy: 0.8933333333333333

In [871]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, Y_train)
rf_predictions = rf_model.predict(X_val)
rf_accuracy = accuracy_score(Y_val, rf_predictions)
print("Forest Accuracy:", rf_accuracy)

Forest Accuracy: 0.94

In [872]:
# test_predictions = dt_model.predict(X_tester)
test_predictions = rf_model.predict(X_tester)
sample_submission = pd.read_csv('submission.csv') 
sample_submission['loan_status'] = test_predictions 
sample_submission.to_csv('my_submission.csv', index=False)